### ISSUE TITLE
怎么调整页面内每个书或电影的大小？

### ISSUE THREAD

**Issue by dongshengme** [bigfa/wp-douban#2]
感觉一个页面里面的单个电影或图书的占位太大了，能不能优化下，或者怎么调大小。谢谢。

**Comment by lifishake** [comment]
以书为例吧，functions.php的108行，<img>是可以加width和height的，或者把medium换成small。
medium是96x155，small是64x103。
再或者改css。

**Comment by dongshengme** [comment]
非常感谢，现在就试下，😋，祝万事顺意

lifishake <notifications@github.com> 于2018年8月15日周三 上午8:04写道：
