### ISSUE TITLE
能否更新采集电影简介呢

### ISSUE THREAD

**Issue by findwisdom** [bigfa/wp-douban#3]
默认左侧是图片缩略图，右边的信息比较少，能否增加电影显示简介功能

**Comment by lifishake** [comment]
api返回值有个summary字段。$data['summary']

**Comment by findwisdom** [comment]
Thanks♪(･ω･)ﾉ。已经成功，我有个大胆的想法，不知道能不能直接在文章编辑页面直接输入地址，采集到的信息直接输入到文章编辑器中，这样能解决图片不能显示缩略图和图片大小排版的问题。

**Comment by lifishake** [comment]
在后台加个框比较简单，在admin_menu里加个钩子，调用add_meta_box函数就行。
按钮的ajax我也会，但怎么往visual画面里加我就没研究了，我从来不用那玩意儿。
