### ISSUE TITLE
后台有数据，前端无法显示

### ISSUE THREAD

**Issue by maNickFry** [bigfa/wp-douban#9]
![0c659c4425fe83cabc324392ab93f3d](https://user-images.githubusercontent.com/40537530/235143034-2f84d833-02fa-414f-95e2-16f90630a1bb.png)
![f73332e6db319ff356c22fc3e81165c](https://user-images.githubusercontent.com/40537530/235143075-bf9fb5c2-93de-485a-b1e0-52bdd3fa4a62.png)
![f0da0d2ceaace2d2ac4f863c4832538](https://user-images.githubusercontent.com/40537530/235143104-b2366bc8-72a5-4404-8801-0356691c0305.png)

**Comment by bigfa** [comment]
你那个shortcode 也不对啊，自己修过吗

**Comment by maNickFry** [comment]
没有修过啊，原来的帮助文档打不开了，我找到别人问的，那人跟我说这样写，插件也没有改动过



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月29日(周六) 晚上9:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [bigfa/wp-douban] 后台有数据，前端无法显示 (Issue #9)




 
你那个shortcode 也不对啊，自己修过吗

**Comment by bigfa** [comment]
这有教程😂。https://fatesinger.com/101050
